commands: refactor a bunch

diff --git a/unixadv/command/get b/unixadv/command/get
--- a/unixadv/command/get
+++ b/unixadv/command/get
@@ -1,26 +1,13 @@
 #!/bin/bash
-set -o nounset
-set -o errexit
-mydir=$(dirname $0)/..
-room=$mydir/location
-inventory=$mydir/inventory
+source $GAMEDIR/library/mainlib.sh
 
 if [ $# -lt 1 ];
 then
     echo "Get what?";
-elif test -e $room/item/$1;
-then
-    # grab item
-    echo "Grabbing item $1";
-    if test -e $room/item/$1/take;
-    then $room/item/$1/take;
-    else
-        mkdir -p $inventory;
-        mv $room/item/$1 $inventory;
-    fi
-elif test -e $room/fixture/$1;
-then
-    echo "That can't be taken.";
+    echo "You see items:"
+    ls $room/item
 else
-    echo "No item $1 in sight";
+    get $1 && echo "Got item $1" \
+    || ( test -e $room/fixture/$1 && echo "Can't take $1" ) \
+    || echo "No item $1 in sight"
 fi
diff --git a/unixadv/command/use b/unixadv/command/use
--- a/unixadv/command/use
+++ b/unixadv/command/use
@@ -1,40 +1,25 @@
 #!/bin/bash
-set -o nounset
-set -o errexit
-mydir=$(dirname $0)/..
-room=$mydir/location
-inventory=$mydir/inventory
+source $GAMEDIR/library/mainlib.sh
 
 if [ $# -lt 1 ];
 then
     echo "Use what?"
     exit 0
-fi
+else
+    item=$1
+    shift
 
-item=$1
-shift
-
-if test -e $inventory/$item;
-then
-    if test -e $inventory/$item/use;
+    if test -e $inventory/$item;
     then
-	echo "Using item $item"
-	$inventory/$item/use $*
-    else
-	echo "Can't use item $item"
-    fi
-elif test -e $room/item/$item;
-then
-    echo "You have to get item $item first"
-elif test -e $room/fixture/$item;
-then
-    if test -e $room/fixture/$item/use;
+	use_item $item && echo "Using item $item" \
+		|| echo "Can't use item $item"
+    elif test -e $room/fixture/$item;
     then
-	echo "Using fixture $item"
-	$room/fixture/$item/use $*
-    else
-	echo "Can't use fixture $item"
+	use_fixture $item && echo "Using fixture $item" \
+		|| echo "Can't use fixture $item"
+    elif test -e $room/item/$item;
+    then echo "You have to get item $item first"
+    else 
+	echo "No item $item in sight"
     fi
-else 
-    echo "No item $item in sight"
 fi
